#!/bin/sh
code --install-extension MaxfieldWalker.vscode-imgur
code --install-extension Rubymaniac.vscode-paste-and-indent
code --install-extension Zignd.html-css-class-completion
code --install-extension abusaidm.html-snippets
code --install-extension boyswan.glsl-literal
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension circledev.glsl-canvas
code --install-extension dariofuzinato.vue-peek
code --install-extension dbaeumer.vscode-eslint
code --install-extension doublefint.pgsql
code --install-extension dzannotti.vscode-babel-coloring
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension Equinusocio.vsc-material-theme
code --install-extension esbenp.prettier-vscode
code --install-extension evanw.glslx-vscode
code --install-extension felixfbecker.php-intellisense
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension generalov.open-in-editor-vscode
code --install-extension HookyQR.beautify
code --install-extension kaiwood.indentation-level-movement
code --install-extension magicstack.MagicPython
code --install-extension mikestead.dotenv
code --install-extension mrmlnc.vscode-attrs-sorter
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.sublime-keybindings
code --install-extension mubaidr.vuejs-extension-pack
code --install-extension octref.vetur
code --install-extension ow.vscode-subword-navigation
code --install-extension redhat.java
code --install-extension reloadedextensions.reloaded-cpp
code --install-extension reloadedextensions.reloaded-themes
code --install-extension sashaweiss.block-travel
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension slevesque.shader
code --install-extension stkb.rewrap
code --install-extension thekalinga.bootstrap4-vscode
code --install-extension tombonnike.vscode-status-bar-format-toggle
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension wholroyd.jinja
code --install-extension xabikos.JavaScriptSnippets
code --install-extension yzhang.markdown-all-in-one
